### ISSUE TITLE
 Socket transferring is not initialised. Please call `tryConnect` function at first.

### ISSUE THREAD

**Issue by tonyshkurenko** [KasperskyLab/Kaspresso#224]
After latest update (1.2.0), our tests started to randomly fail (after test completes). We don't use adb server, because firebase test lab doesn't allow us to, but still it fails.

Init of tests is simple, no extra stuff:

`abstract class BaseInstrumentedTest : TestCase(Kaspresso.Builder.simple()) {`

Stacktrace:

```
java.lang.IllegalStateException: Socket transferring is not initialised. Please call `tryConnect` function at first.
at com.kaspersky.adbserver.connection.implementation.ConnectionClientImplBySocket.getSocketMessagesTransferring(ConnectionClientImplBySocket.kt:37)
at com.kaspersky.adbserver.connection.implementation.ConnectionClientImplBySocket.access$getSocketMessagesTransferring$p(ConnectionClientImplBySocket.kt:18)
at com.kaspersky.adbserver.connection.implementation.ConnectionClientImplBySocket$tryDisconnectCommon$1.invoke(ConnectionClientImplBySocket.kt:103)
at com.kaspersky.adbserver.connection.implementation.ConnectionClientImplBySocket$tryDisconnectCommon$1.invoke(ConnectionClientImplBySocket.kt:18)
at com.kaspersky.adbserver.connection.implementation.ConnectionMaker.disconnect(ConnectionMaker.kt:60)
at com.kaspersky.adbserver.connection.implementation.ConnectionClientImplBySocket.tryDisconnectCommon(ConnectionClientImplBySocket.kt:102)
at com.kaspersky.adbserver.connection.implementation.ConnectionClientImplBySocket.tryDisconnect(ConnectionClientImplBySocket.kt:97)
at com.kaspersky.adbserver.device.Device.stopConnectionToDesktop(Device.kt:59)
at com.kaspersky.adbserver.device.AdbTerminal.disconnect(AdbTerminal.kt:20)
at com.kaspersky.kaspresso.device.server.AdbServerImpl.disconnectServer(AdbServerImpl.kt:87)
at com.kaspersky.kaspresso.testcases.core.TestRunner.run(TestRunner.kt:87)
at com.kaspersky.kaspresso.testcases.core.sections.MainTestSection.run(MainTestSection.kt:29)
at com.xxx.BaseInstrumentedTest.test(BaseInstrumentedTest.kt:69)
at com.xxx.BaseInstrumentedTest.test$default(BaseInstrumentedTest.kt:59)
at com.xxx.xxx.xxx.xxx.test_name(xxx.kt:79)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)

```

**Comment by matzuk** [comment]
Hi @tonyshkurenko!
Thanks for the bug =)
So, the bug must be actual for older versions of Kaspresso, too =(
The root cause is `SystemDialogSafetyProviderImpl`. This provider is introduced in interceptors struggling with unexpected system dialogs (`SystemDialogSafetyViewBehaviorInterceptor`, `SystemDialogSafetyDataBehaviorInterceptor`, `SystemDialogSafetyWebBehaviorInterceptor`, `SystemDialogSafetyObjectBehaviorInterceptor`, `SystemDialogSafetyDeviceBehaviorInterceptor`). 
So, your test had some flakes that's why mentioned interceptors were called. 

Shortly, it's a bug. In one-two days we are going to prepare a fix, and you will be able to use [snapshot-version](https://github.com/KasperskyLab/Kaspresso#snapshots) with the fixed bug.

**Comment by matzuk** [comment]
I forgot the second necessary condition. Besides flakes, your test has to "meet" system dialogs when Kaspresso tries to overcome flakies.

**Comment by matzuk** [comment]
@tonyshkurenko ready.
You can try the Snapshot version.
