### ISSUE TITLE
java.lang.NoSuchMethodError: No direct method <init>

### ISSUE THREAD

**Issue by averyzhong** [KasperskyLab/Kaspresso#235]
java.lang.NoSuchMethodError: No direct method <init>(ILjava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V in class Lkotlin/jvm/internal/FunctionReferenceImpl; or its super classes (declaration of 'kotlin.jvm.internal.FunctionReferenceImpl' appears in /data/app/com.example.uiautotesting-UcmbPSk0JidLiWAO3L7_Ow==/base.apk)
	at com.kaspersky.kaspresso.interceptors.tolibrary.LibraryInterceptorsInjector$injectKaspressoInKakao$1$1$1.<init>(Unknown Source:10)
	at com.kaspersky.kaspresso.interceptors.tolibrary.LibraryInterceptorsInjector$injectKaspressoInKakao$1$1.invoke(LibraryInterceptorsInjector.kt:54)
	at com.kaspersky.kaspresso.interceptors.tolibrary.LibraryInterceptorsInjector$injectKaspressoInKakao$1$1.invoke(LibraryInterceptorsInjector.kt:22)
	at com.agoda.kakao.intercept.Interceptor$Configurator.onViewInteraction(Interceptor.kt:116)
	at com.kaspersky.kaspresso.interceptors.tolibrary.LibraryInterceptorsInjector$injectKaspressoInKakao$1.invoke(LibraryInterceptorsInjector.kt:53)
	at com.kaspersky.kaspresso.interceptors.tolibrary.LibraryInterceptorsInjector$injectKaspressoInKakao$1.invoke(LibraryInterceptorsInjector.kt:22)
	at com.agoda.kakao.Kakao.intercept(Kakao.kt:35)
	at com.kaspersky.kaspresso.interceptors.tolibrary.LibraryInterceptorsInjector.injectKaspressoInKakao(LibraryInterceptorsInjector.kt:52)
	at com.kaspersky.kaspresso.kaspresso.Kaspresso$Builder.build$kaspresso_release(Kaspresso.kt:739)
	at com.kaspersky.kaspresso.testcases.api.testcase.BaseTestCase.<init>(BaseTestCase.kt:33)
	at com.kaspersky.kaspresso.testcases.api.testcase.BaseTestCase.<init>(BaseTestCase.kt:30)
	at com.kaspersky.kaspresso.testcases.api.testcase.TestCase.<init>(TestCase.kt:13)
	at com.kaspersky.kaspresso.testcases.api.testcase.TestCase.<init>(TestCase.kt:12)
	at com.example.uiautotesting.MainActivityTest.<init>(MainActivityTest.kt:16)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2251)

**Comment by matzuk** [comment]
@averyzhong Hi!
We work on this topic. I can suggest you a temporary solution - up the kotlin library to version 1.4
