### ISSUE TITLE
kaspresso-compose-support 1.4.2

### ISSUE THREAD

**Issue by PaladiRka** [KasperskyLab/Kaspresso#397]
After update compose support lib to 1.4.2 all tests fail with:

```
java.lang.AbstractMethodError: abstract method "kotlin.coroutines.CoroutineContext$Key androidx.compose.runtime.MonotonicFrameClock.getKey()"
at kotlin.coroutines.CoroutineContext$plus$1.invoke(CoroutineContext.kt:33)
at kotlin.coroutines.CoroutineContext$plus$1.invoke(CoroutineContext.kt:32)
at kotlin.coroutines.CoroutineContext$Element$DefaultImpls.fold(CoroutineContext.kt:70)
at androidx.compose.runtime.MonotonicFrameClock$DefaultImpls.fold(MonotonicFrameClock.kt:27)
at androidx.compose.ui.test.TestMonotonicFrameClock.fold(TestMonotonicFrameClock.jvm.kt:62)
at kotlin.coroutines.CoroutineContext$DefaultImpls.plus(CoroutineContext.kt:32)
at kotlin.coroutines.CoroutineContext$Element$DefaultImpls.plus(CoroutineContext.kt:59)
at kotlin.coroutines.AbstractCoroutineContextElement.plus(CoroutineContextImpl.kt:14)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.<init>(ComposeUiTest.android.kt:248)
at androidx.compose.ui.test.junit4.AndroidComposeTestRule$special$$inlined$AndroidComposeUiTestEnvironment$1.<init>(ComposeUiTest.android.kt:203)
at androidx.compose.ui.test.junit4.AndroidComposeTestRule.<init>(AndroidComposeTestRule.android.kt:212)
at androidx.compose.ui.test.junit4.AndroidComposeTestRule_androidKt.createAndroidComposeRule(AndroidComposeTestRule.android.kt:78)
at androidx.compose.ui.test.junit4.AndroidComposeTestRule_androidKt.createComposeRule(AndroidComposeTestRule.android.kt:212)
at MyClass.<init>(UITest.kt:81)

```
UITest.kt:81:
```
 var composeTestRule: ComposeContentTestRule? = createComposeRule()
```

**Comment by Nikitae57** [comment]
Hi, @PaladiRka! Difficult to say what's wrong without the code. Please, try to update to the latest kotlin and Kaspresso releases and re-open if the issue still persists
