### ISSUE TITLE
Allure Support: testInstrumentationRunner cannot be extended

### ISSUE THREAD

**Issue by cee-dee** [KasperskyLab/Kaspresso#492]
For integrating additional testing tools like TestButler or Facebook's Screenshot Testing it is necessary to use a custom TestRunner. For Kaspresso to make use of the Allure Reports, it is necessary to use `io.qameta.allure.android.runners.AllureAndroidJUnitRunner`. In the `androidTest` code one does not have access to `AllureAndroidJUnitRunner`, so it is neither possible to create an instance of it nor to extend that class.

```
import android.os.Bundle
import androidx.test.runner.AndroidJUnitRunner
import io.qameta.allure.android.runners.AllureAndroidJUnitRunner

class OwnRunner : AndroidJUnitRunner() {

    override fun onCreate(arguments: Bundle) {
        super.onCreate(arguments)
        ...
    }
}
```
will not compile because it complains about missing classes from `io.qameta.*`.

Strangely, specifying 
```
testInstrumentationRunner "io.qameta.allure.android.runners.AllureAndroidJUnitRunner"
```
in the `build.gradle` file perfectly allows Allure to launch that runner. Especially, the test reports are properly generated and stored.

It seems to be (partially) a compile time issue (which makes the problem even stranger):
```
class OwnRunner : AndroidJUnitRunner() {

    override fun onCreate(arguments: Bundle) {
        super.onCreate(arguments)
        Class.forName("io.qameta.allure.android.runners.AllureAndroidJUnitRunner")
        ...
    }
}
```
The above code does not crash, meaning `Class.forName(...)` returns an actual instance, meaning that `AllureAndroidJUnitRunner` actually is on the classpath. (Of course I configured this to be the testInstrumentationRunner to use)

So, I tried replicating the Allure Runner to by-pass that restriction by copying the code from the `allure-android` project:
```
class OwnRunner : AndroidJUnitRunner() {

    override fun onCreate(arguments: Bundle) {
        arguments.putCharSequence("listener", arguments.getCharSequence("listener")
            ?.let {
                "$it,$allureAndroidListenerClassName"
            }
            ?: allureAndroidListenerClassName)
        super.onCreate(arguments)
    }

    companion object {
        private const val allureAndroidListenerClassName = "io.qameta.allure.espresso.AllureAndroidListener"
    }
}
```
But now I'm getting this error:
```
java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{com.example.test/com.example.OwnRunner}: java.lang.IllegalArgumentException: Could not find extra class io.qameta.allure.espresso.AllureAndroidListener
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5868)
	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalArgumentException: Could not find extra class io.qameta.allure.espresso.AllureAndroidListener
	at androidx.test.internal.runner.RunnerArgs$Builder.loadClassByNameInstantiateAndAdd(RunnerArgs.java:620)
	at androidx.test.internal.runner.RunnerArgs$Builder.parseLoadAndInstantiateClasses(RunnerArgs.java:547)
	at androidx.test.internal.runner.RunnerArgs$Builder.fromBundle(RunnerArgs.java:282)
	at androidx.test.runner.AndroidJUnitRunner.parseRunnerArgs(AndroidJUnitRunner.java:393)
	at androidx.test.runner.AndroidJUnitRunner.onCreate(AndroidJUnitRunner.java:302)
	at com.example.OwnRunner.onCreate(HomesTestRunner.kt:20)

```

The above exception looks like `AllureAndroidListener` is not on the classpath. So I changed my runner to verify this:
```
class HomesTestRunner : AndroidJUnitRunner() {

    override fun onCreate(arguments: Bundle) {
        Class.forName("io.qameta.allure.android.runners.AllureAndroidListener")
        super.onCreate(arguments)
    }
}
```
which confirmed that the `AllureAndroidListener` is not on the classpath:
```
java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{com.example.test/com.example.OwnTestRunner}: java.lang.ClassNotFoundException: io.qameta.allure.android.runners.AllureAndroidListener
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5868)
	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ClassNotFoundException: io.qameta.allure.android.runners.AllureAndroidListener
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at java.lang.Class.forName(Class.java:378)
	at com.example.OwnTestRunner.onCreate(HomesTestRunner.kt:14)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5863)
	at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loop(Looper.java:193) 
	at android.app.ActivityThread.main(ActivityThread.java:6669) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
Caused by: java.lang.ClassNotFoundException: Didn't find class "io.qameta.allure.android.runners.AllureAndroidListener" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.test-E8vB592t7AyXiCIu9358TA==/base.apk", zip file "/data/app/com.example-zijRXPeFmblVpTC1zFvZNw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test-E8vB592t7AyXiCIu9358TA==/lib/arm64, /data/app/com.example.-zijRXPeFmblVpTC1zFvZNw==/lib/arm64, /data/app/com.example.test-E8vB592t7AyXiCIu9358TA==/base.apk!/lib/arm64-v8a, /data/app/com.example-zijRXPeFmblVpTC1zFvZNw==/base.apk!/lib/arm64-v8a, /system/lib64]]
```

Expected behavior: For extensibility reasons I'd like to have a way how I can combine Kaspresso/Allure together with other Test Runners.

If anyone can give me a workaround, this already would help me.

**Comment by Nikitae57** [comment]
Hi, @cee-dee! Thank you for your submission! In the 1.5.1 release we've introduced KaspressoRunner to mitigate the  storage restrictions which didn't allow us to generate proper allure reports. Unfortunately we missed a bug which causes it to work incorrectly on the devices with API lower than 30. It's fixed in master, but it hasn't been released yet. If it's not a problem for you, you could update kaspresso version you're using up to 1.5.1 and extend the  KaspressoRunner which extends the AllureRunner. Otherwise I would suggest you to wait for 1.5.2

**Comment by cee-dee** [comment]
We need to wait for 1.5.2 since we're running tests on devices with API level lower than 30.
Anyway, many thanks for addressing the issue. I'll let you know if it's working then! 👍

**Comment by Nikitae57** [comment]
Hi, @cee-dee! Have you tried 1.5.2?

**Comment by Nikitae57** [comment]
Closing since test runner is extendable now

**Comment by cee-dee** [comment]
Thank you for following up. Actually, I've just started reviving our UI tests. I will let you know about the results! Thanks again!
