### ISSUE TITLE
WRITE_EXTERNAL_STORAGE cannot be granted at DocLocScreenshotTestCase for 29+ API devices

### ISSUE THREAD

**Issue by zhkvdm** [KasperskyLab/Kaspresso#654]
DocLocScreenshotTestCase requests WRITE_EXTERNAL_STORAGE for every devices, but it cannot be granted for 29+ API devices.

Run DocLocScreenshotTestCase test at emulator 31 API.

Test fails with exception:
```
Permission: android.permission.WRITE_EXTERNAL_STORAGE cannot be granted!
junit.framework.AssertionFailedError: Failed to grant permissions, see logcat for details (Ask Gemini)
                 	at junit.framework.Assert.fail(Assert.java:50)
                 	at androidx.test.runner.permission.PermissionRequester.requestPermissions(PermissionRequester.java:111)
                 	at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:135)
                 	at com.kaspersky.kaspresso.docloc.rule.ToggleNightModeRule$apply$1.evaluate(ToggleNightModeRule.kt:33)
                 	at com.kaspersky.kaspresso.docloc.rule.LocaleRule.changeLanguageInApp(LocaleRule.kt:47)
                 	at com.kaspersky.kaspresso.docloc.rule.LocaleRule.access$changeLanguageInApp(LocaleRule.kt:14)
                 	at com.kaspersky.kaspresso.docloc.rule.LocaleRule$apply$1.evaluate(LocaleRule.kt:34)
                 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
                 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
                 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
                 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
                 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
                 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
                 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
                 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
                 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
                 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
                 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
                 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
                 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
                 	at org.junit.runners.Suite.runChild(Suite.java:128)
                 	at org.junit.runners.Suite.runChild(Suite.java:27)
                 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
                 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
                 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
                 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
                 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
                 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
                 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
                 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
                 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
                 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
                 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2248)
```

**Comment by Nikitae57** [comment]
Hi! WRITE_EXTERNAL_STORAGE certainly could be granted on API 29+. Please, check if you have such permission declaired in the manifest. If it is, then try to grant the permission through the rule e.g.
```kotlin
@get:Rule
val runtimePermissionRule: GrantPermissionRule = GrantPermissionRule.grant(
    Manifest.permission.WRITE_EXTERNAL_STORAGE,
    Manifest.permission.READ_EXTERNAL_STORAGE
)
```

If these steps doesn;t help, please, re-open the issue
